# Generated by Django 4.1.7 on 2023-12-15 23:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('backup_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='Bookmark', to='users.bookmark')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Users', to='users.user'),
        ),
    ]
