# Generated by Django 4.1.7 on 2023-12-22 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_pages_options_alter_tags_options_and_more'),
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.pages'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
