# Generated by Django 4.1.7 on 2023-12-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_bookmark_users_remove_user_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
