# Generated by Django 4.1.7 on 2023-12-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_bookmark_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
