# Generated by Django 4.0.4 on 2023-12-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Testtitle', max_length=255),
            preserve_default=False,
        ),
    ]
