# Generated by Django 4.0.4 on 2023-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='word',
        ),
        migrations.AddField(
            model_name='keyword',
            name='back',
            field=models.TextField(default='back'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='front',
            field=models.TextField(default='front'),
            preserve_default=False,
        ),
    ]
