# Generated by Django 4.0.4 on 2023-12-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_keyword_word_keyword_back_keyword_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='title',
            field=models.CharField(default='test title', max_length=255),
            preserve_default=False,
        ),
    ]
