# Generated by Django 5.0.1 on 2024-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_flashcard_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
