# Generated by Django 5.1.3 on 2024-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_tags_flashcards'),
        ('quizzes', '0007_alter_quiz_options_alter_quizanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Flashcard', to='info.tags'),
        ),
    ]
