# Generated by Django 4.1.7 on 2023-12-15 23:17

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pages', models.ManyToManyField(blank=True, related_name='Tags', to='info.pages')),
            ],
            options={
                'db_table': 'info_tags',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pages',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Pages', to='info.tags'),
        ),
    ]
