# Generated by Django 4.1.7 on 2023-12-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_pages_options_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_creaated',
            new_name='date_created',
        ),
    ]
