# Generated by Django 5.1.3 on 2024-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_rename_date_creaated_comment_date_created'),
        ('quizzes', '0007_alter_quiz_options_alter_quizanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='flashcards',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='quizzes.flashcard'),
        ),
    ]
